version: "3"
services:
  db:
    image: mysql:5.7
    container_name: mysql57
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: sneha
      MYSQL_PASSWORD: devpass
    ports:
      - 3308:3306
  apacheos:
    build:
      context: ./myFile
      dockerfile: Dockerfile
    container_name: php72
    restart: always
    depends_on:
      - db
    ports:
      - 8000:80
    volumes:
      - ./myFile:/var/www/html
